- hosts: masterpoint.io
  tasks:
    - name: Update code
      git: repo=https://github.com/Gowiem/masterpoint.io.git dest=~/masterpoint.io

    - name: Install pip, python-dev package with apt
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-dev
        - python-pip

    # Upgrade pip with pip to fix angstwad/docker.ubuntu/pull/35 and docker-py/issues/525
    # Install latest version when no specific release is set.
    - name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
      pip:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - { name: pip, version: "latest", install: true }
        - { name: setuptools, version: "latest", install: true }
        - { name: docker-py, version: "latest", install: true }
        - { name: docker-compose, version: "latest", install: true }
      when: (item.version=="latest" and item.install)
      ignore_errors: yes

    # Install specific version when set in the variables
    - name: Install specific pip, setuptools, docker-py and docker-compose with pip
      pip:
        name: "{{ item.name }}"
        state: present
        version: "{{ item.version }}"
      with_items:
        - { name: pip, version: "latest", install: "true" }
        - { name: setuptools, version: "latest", install: "true" }
        - { name: docker-py, version: "latest", install: "true" }
        - { name: docker-compose, version: "latest", install: "true" }
      when: (item.version!="latest" and item.install)

    - docker_service:
        project_src: masterpoint.io
        state: absent

    - docker_service:
        project_src: masterpoint.io
        state: present
        build: yes
